In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
non_violence_data = pd.read_csv("../non_violence_data.csv")
violence_data = pd.read_csv("../violence_data.csv")

In [9]:
non_violence_data

,frame_index,timestamp,person1_id,person2_id,box1_x_min,box1_y_min,box1_x_max,box1_y_max,box2_x_min,box2_y_min,...,relative_kp12_x,relative_kp12_y,relative_kp13_x,relative_kp13_y,relative_kp14_x,relative_kp14_y,relative_kp15_x,relative_kp15_y,relative_kp16_x,relative_kp16_y
0,0,0.000000,0,1,0.000000,0.070370,0.036346,0.223611,0.077942,0.070602,...,0.084106,0.004572,0.075226,-0.008449,0.090088,0.179630,0.106934,0.214815,0.000000,0.000000
1,0,0.000000,0,2,0.000000,0.070370,0.036346,0.223611,0.084839,0.164583,...,-0.005615,-0.112211,0.076752,-0.001157,0.118652,0.189352,0.098816,0.176042,0.109802,0.176968
2,0,0.000000,1,2,0.077942,0.070602,0.111511,0.207176,0.084839,0.164583,...,-0.089722,-0.116782,0.001526,0.007292,0.028564,0.009722,-0.008118,-0.038773,0.109802,0.176968
3,4,0.133333,0,1,0.000092,0.070255,0.037964,0.223495,0.078369,0.070833,...,0.084740,0.004745,0.073532,-0.020370,0.088379,0.170602,0.106201,0.211343,0.088806,0.213657
4,4,0.133333,0,3,0.000092,0.070255,0.037964,0.223495,0.006866,0.194676,...,-0.003883,-0.099306,0.070969,-0.015509,0.114929,0.170370,0.112854,0.171296,0.113770,0.162037
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12964,146,4.866667,838,843,1.066964,0.646205,2.852679,2.193080,0.000279,1.247768,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
12965,149,4.966667,838,843,1.037946,0.642299,2.857143,2.191964,0.000279,1.310268,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
12966,153,5.100000,838,844,0.978237,0.635603,2.857143,2.194196,0.000558,1.214286,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
12967,154,5.133333,838,844,0.929129,0.633929,2.852679,2.194196,0.000000,1.142857,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
12968,157,5.233333,838,845,0.857701,0.629464,2.852679,2.187500,0.000279,1.061942,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [10]:
violence_data["label"] = 1
non_violence_data["label"] = 0

In [11]:
data = pd.concat([violence_data, non_violence_data], ignore_index=True)

In [13]:
X = data.drop(columns=[ 'frame_index','timestamp','person1_id', 'person2_id', 'person1_kp0_x', 'person1_kp0_y',
 'person1_kp1_x',
 'person1_kp1_y',
 'person1_kp2_x',
 'person1_kp2_y',
 'person1_kp3_x',
 'person1_kp3_y',
 'person1_kp4_x',
 'person1_kp4_y','person2_kp0_x',
 'person2_kp0_y',
 'person2_kp1_x',
 'person2_kp1_y',
 'person2_kp2_x',
 'person2_kp2_y',
 'person2_kp3_x',
 'person2_kp3_y',
 'person2_kp4_x',
 'person2_kp4_y','relative_kp0_x',
 'relative_kp0_y',
 'relative_kp1_x',
 'relative_kp1_y',
 'relative_kp2_x',
 'relative_kp2_y',
 'relative_kp3_x',
 'relative_kp3_y',
 'relative_kp4_x',
 'relative_kp4_y','label'])

In [14]:
Y = data['label']

In [16]:
from sklearn.model_selection import train_test_split

In [32]:
x_train, x_val, y_train, y_val = train_test_split(X, Y, test_size=0.2, random_state=42)

In [23]:
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler

In [25]:
SS = StandardScaler()
X = SS.fit_transform(X)

In [ ]:
from sklearn.linear_model import LogisticRegression
log_params = {
    "C": [0.01, 1, 100],                 # Small, medium, large regularization
    "penalty": ["l1", "l2"],             # L1 (sparse), L2 (default, stable)
    "solver": ["liblinear", "saga"],     # Supports L1 + L2
    "max_iter": [1000],                  # High enough to ensure convergence
    "class_weight": [None, "balanced"]   # Handle imbalance
}


log_model = LogisticRegression()

grid_search = GridSearchCV(log_model, log_params, cv = 10, scoring='accuracy', verbose=2, n_jobs=-1)
grid_search.fit(X, Y)

print(f"Best Params: {grid_search.best_params_}")
print(f"Best Score: {grid_search.best_score_}")

Fitting 10 folds for each of 24 candidates, totalling 240 fits
Best Params: {'C': 0.01, 'class_weight': 'balanced', 'max_iter': 1000, 'penalty': 'l1', 'solver': 'liblinear'}
Best Score: 0.9297032045307908

In [34]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

logestic = LogisticRegression(C= 0.01, class_weight= 'balanced', max_iter = 1000, penalty = 'l1', solver = 'liblinear')
logestic.fit(x_train, y_train)
y_pred = logestic.predict(x_val)

print("Accuracy:", accuracy_score(y_val, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_val, y_pred))
print("Classification Report:\n", classification_report(y_val, y_pred))

Accuracy: 0.9564204148217199
Confusion Matrix:
 [[2515   61]
 [ 126 1589]]
Classification Report:
               precision    recall  f1-score   support

           0       0.95      0.98      0.96      2576
           1       0.96      0.93      0.94      1715

    accuracy                           0.96      4291
   macro avg       0.96      0.95      0.95      4291
weighted avg       0.96      0.96      0.96      4291

In [ ]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier(
    criterion='gini',
    max_depth=None,
    class_weight='balanced',
    random_state=42
)

In [14]:
model.fit(x_train, y_train)
y_pred = model.predict(x_val)

In [15]:
print("Accuracy:", accuracy_score(y_val, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_val, y_pred))
print("Classification Report:\n", classification_report(y_val, y_pred))

Accuracy: 0.9565143995408353
Confusion Matrix:
 [[33918  1125]
 [ 1451 22744]]
Classification Report:
               precision    recall  f1-score   support

           0       0.96      0.97      0.96     35043
           1       0.95      0.94      0.95     24195

    accuracy                           0.96     59238
   macro avg       0.96      0.95      0.95     59238
weighted avg       0.96      0.96      0.96     59238

In [29]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
model = RandomForestClassifier(
    n_estimators=100,
    criterion='gini',
    max_depth=None,
    min_samples_split=2,
    min_samples_leaf=1,
    class_weight='balanced',
    random_state=42
)

In [31]:
model.fit(x_train, y_train)
y_pred = model.predict(x_val)

In [20]:
import joblib

In [21]:
joblib.dump(model, 'random_forest_model.pkl')

['random_forest_model.pkl']

In [19]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print("Accuracy:", accuracy_score(y_val, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_val, y_pred))
print("Classification Report:\n", classification_report(y_val, y_pred))

Accuracy: 0.98911171882913
Confusion Matrix:
 [[34598   445]
 [  200 23995]]
Classification Report:
               precision    recall  f1-score   support

           0       0.99      0.99      0.99     35043
           1       0.98      0.99      0.99     24195

    accuracy                           0.99     59238
   macro avg       0.99      0.99      0.99     59238
weighted avg       0.99      0.99      0.99     59238

In [ ]:
import os
import pandas as pd
from tqdm import tqdm
from IPython.display import clear_output

In [38]:
sample_files= ["t_n001_converted.avi"]
sample_file_path = ".."

In [40]:
import sys
import os

# go one step up to project root
sys.path.append(os.path.abspath(".."))

In [ ]:
from backend.pipeline import ViolenceFeatureExtractor
from backend.utils.data_preprocessing import preprocess_data

# Absolute paths to your models
detection_model_path = "backend/models/yolo8n.pt"
pose_model_path = "backend/models/yolo8n.pt"

# Check if the model files exist
if not os.path.exists(detection_model_path):
    raise FileNotFoundError(f"Detection model not found at {detection_model_path}")

if not os.path.exists(pose_model_path):
    raise FileNotFoundError(f"Pose model not found at {pose_model_path}")

# Initialize the feature extractor
extractor = ViolenceFeatureExtractor()

# Path to the final CSV where data will be appended
final_csv_path = 'sample.csv'

# Path to save the output CSV
output_csv_path = 'extracted_feature_data/sample.csv'

full_log = []

# tqdm loop with description
for video_name in tqdm(sample_files, desc="Processing Videos"):
    try:
        extractor.reset()
        video_path = os.path.join(sample_file_path, video_name)

        print(f"\n📹 Processing video: {video_name}")
        frame_width, frame_height, interaction_count = extractor.process_video(
            video_path,
            output_csv_path,
            output_folder=None,
            show_video=False,
            save_video=False
        )
        clear_output(wait=True)

        df_csv = pd.read_csv(output_csv_path)
        df_preprocessed, expected_columns = preprocess_data(df_csv, frame_width, frame_height)

        # Skip appending if there are no interactions (empty dataframe)
        if df_preprocessed.empty:
            log_entry = f"❌ {video_name}: No interactions found"
            print(log_entry)
            full_log.append(log_entry)
            continue  # Skip to the next video

        # Check if the final CSV exists and has data
        if os.path.exists(final_csv_path) and os.path.getsize(final_csv_path) > 0:
            # Append to the existing CSV
            df_preprocessed.to_csv(final_csv_path, mode='a', header=False, index=False)
        else:
            # Create a new CSV with the appropriate header
            df_preprocessed.to_csv(final_csv_path, mode='w', header=True, index=False)

        log_entry = f"✅ {video_name}: {len(df_preprocessed)} interactions saved"
        print(log_entry)

    except Exception as e:
        log_entry = f"❌ Error processing {video_name}: {e}"
        print(log_entry)

    full_log.append(log_entry)

ModuleNotFoundError: No module named 'backend.utils.feature_extraction'

In [2]:
sample_data = pd.read_csv("sample.csv")

In [3]:
X = sample_data.drop(columns=[ 'video_name','frame_index','timestamp','person1_id', 'person2_id', 'person1_kp0_x', 'person1_kp0_y',
 'person1_kp1_x',
 'person1_kp1_y',
 'person1_kp2_x',
 'person1_kp2_y',
 'person1_kp3_x',
 'person1_kp3_y',
 'person1_kp4_x',
 'person1_kp4_y','person2_kp0_x',
 'person2_kp0_y',
 'person2_kp1_x',
 'person2_kp1_y',
 'person2_kp2_x',
 'person2_kp2_y',
 'person2_kp3_x',
 'person2_kp3_y',
 'person2_kp4_x',
 'person2_kp4_y','relative_kp0_x',
 'relative_kp0_y',
 'relative_kp1_x',
 'relative_kp1_y',
 'relative_kp2_x',
 'relative_kp2_y',
 'relative_kp3_x',
 'relative_kp3_y',
 'relative_kp4_x',
 'relative_kp4_y'])

In [4]:
X[0:1]

,box1_x_min,box1_y_min,box1_x_max,box1_y_max,box2_x_min,box2_y_min,box2_x_max,box2_y_max,center1_x,center1_y,...,relative_kp12_x,relative_kp12_y,relative_kp13_x,relative_kp13_y,relative_kp14_x,relative_kp14_y,relative_kp15_x,relative_kp15_y,relative_kp16_x,relative_kp16_y
0,0.281944,0.113281,0.447685,0.270573,0.151389,0.165625,0.259259,0.25,0.364815,0.191927,...,-0.139583,0.027995,-0.164583,0.017839,-0.15162,0.009635,-0.156829,0.007161,-0.127778,-0.005078

In [36]:
sample_predict = model.predict(X)

In [37]:
sample_predict

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0], dtype=int64)

In [33]:
pred_list = sample_predict.tolist()

In [34]:
pred_list

[0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0]

In [38]:
count_0 = pred_list.count(0)
count_1 = pred_list.count(1)

print(f"Count of 0s: {count_0}")
print(f"Count of 1s: {count_1}")

Count of 0s: 350
Count of 1s: 31

In [5]:
import pandas as pd
from backend.utils.prediction import predict

In [ ]:



result = predict(X)
print("Classification result:", result)

Classification result: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0]

In [29]:
trimmed_list = result[91:]

In [31]:
trimmed_list.count(0)

17

In [ ]:
from ultralytics import YOLO
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"

model = YOLO("yolo11n.pt")
model.to(device)
results = model(
    "NV_1.mp4",
    stream=True,     # 🔑 IMPORTANTArithmeticError
    device=0 if device == "cuda" else "cpu"
)
all_rows = []

for frame_id, r in enumerate(results):
    if r.boxes is None:
        continue

    for box in r.boxes:
        conf = float(box.conf)
        if conf < 0.4:     # confidence threshold
            continue

        all_rows.append({
            "frame": frame_id,
            "class": int(box.cls),
            "confidence": conf,
            "bbox": box.xyxy[0].tolist()
        })

Downloading https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11n-pose.pt to 'yolo11n-pose.pt': 100% ━━━━━━━━━━━━ 6.0MB 17.2MB/s 0.3s.3s<0.0s5s

In [10]:
from ultralytics import YOLO
import torch

device = 0 if torch.cuda.is_available() else "cpu"

model = YOLO("yolo11n-pose.pt")

results = model(
    "NV_1.mp4",
    stream=True,
    device=device
)

for r in results:
    if r.keypoints is not None:
        print(r.keypoints.xy)

video 1/1 (frame 1/66) /home/mcqueen/Documents/YoloV8-LSTM-video-Classification/notebooks/NV_1.mp4: 384x640 2 persons, 9.8ms
tensor([[[ 975.0547,  310.4874],
         [ 978.0482,  292.4034],
         [ 971.8413,  296.9894],
         [1006.3462,  281.4768],
         [1001.8779,  294.5704],
         [1071.6116,  340.6323],
         [1034.6040,  364.5307],
         [1087.2174,  440.3827],
         [1053.7925,  488.0798],
         [ 998.8053,  501.0053],
         [ 999.3876,  533.6619],
         [1097.1875,  595.5475],
         [1062.0364,  600.9114],
         [1114.2678,  778.8793],
         [1025.1034,  786.6360],
         [1184.9449,  965.3563],
         [1049.8397,  966.5891]],

        [[ 966.5112,  307.5669],
         [ 964.5973,  291.0264],
         [ 957.1908,  292.3019],
         [ 927.3529,  289.8405],
         [ 922.6133,  293.0680],
         [ 891.2120,  365.1638],
         [ 898.5276,  376.8808],
         [ 882.1154,  490.5658],
         [ 913.9731,  511.1818],
         [ 936.2170,  529.3185],
         [ 961.6854,  526.6660],
         [ 894.7013,  605.3726],
         [ 901.1955,  614.0298],
         [ 887.3829,  789.3582],
         [ 902.6204,  803.6578],
         [ 886.2358,  974.0112],
         [ 894.6681,  991.7468]]], device='cuda:0')
video 1/1 (frame 2/66) /home/mcqueen/Documents/YoloV8-LSTM-video-Classification/notebooks/NV_1.mp4: 384x640 2 persons, 7.9ms
tensor([[[ 971.6025,  314.7441],
         [ 973.7000,  297.0745],
         [ 969.7012,  301.1788],
         [1002.6370,  284.3907],
         [1003.8848,  296.7283],
         [1069.0458,  340.6325],
         [1035.9883,  364.2439],
         [1079.8694,  440.7864],
         [1054.6155,  487.2286],
         [ 992.8434,  500.7824],
         [ 997.6419,  528.0203],
         [1096.3844,  597.0921],
         [1063.0996,  602.2630],
         [1111.5757,  779.6213],
         [1019.5327,  787.6813],
         [1185.4072,  965.8285],
         [1047.6469,  966.3638]],

        [[ 967.0270,  309.4995],
         [ 965.0788,  293.1915],
         [ 958.5363,  294.2377],
         [ 928.2478,  292.0233],
         [ 926.7603,  294.8027],
         [ 893.9424,  366.3421],
         [ 901.4500,  377.9860],
         [ 883.3835,  489.9609],
         [ 917.7980,  510.2261],
         [ 936.7916,  530.2174],
         [ 963.0094,  525.5946],
         [ 895.4462,  606.9908],
         [ 901.9581,  615.4362],
         [ 889.0408,  789.3920],
         [ 901.8843,  803.8958],
         [ 885.7484,  973.7703],
         [ 894.6198,  991.2310]]], device='cuda:0')
video 1/1 (frame 3/66) /home/mcqueen/Documents/YoloV8-LSTM-video-Classification/notebooks/NV_1.mp4: 384x640 2 persons, 7.7ms
tensor([[[ 969.9817,  317.7745],
         [ 971.0647,  300.4226],
         [ 969.2869,  303.9235],
         [1000.4855,  285.9266],
         [1007.3534,  297.4315],
         [1070.3538,  340.9254],
         [1036.8488,  362.0491],
         [1081.0010,  446.7677],
         [1053.1562,  488.6089],
         [ 992.1927,  498.2277],
         [ 995.9878,  524.7145],
         [1093.6250,  598.6844],
         [1059.9783,  602.6703],
         [1111.0867,  782.0663],
         [1016.9110,  788.6223],
         [1185.3473,  966.2764],
         [1047.1902,  965.9277]],

        [[ 963.1346,  312.1893],
         [ 960.5337,  295.6953],
         [ 955.8719,  296.5257],
         [ 922.5984,  293.5099],
         [ 928.9041,  296.2902],
         [ 890.2302,  366.3623],
         [ 905.2048,  377.7789],
         [ 879.4934,  491.0790],
         [ 920.6295,  510.2628],
         [ 934.7108,  528.5485],
         [ 963.2675,  521.9606],
         [ 891.7656,  607.3118],
         [ 903.2510,  615.6405],
         [ 887.1155,  789.8900],
         [ 902.4504,  804.5733],
         [ 884.3923,  973.7650],
         [ 895.0184,  991.5380]]], device='cuda:0')
video 1/1 (frame 4/66) /home/mcqueen/Documents/YoloV8-LSTM-video-Classification/notebooks/NV_1.mp4: 384x640 2 persons, 9.3ms
tensor([[[ 973.0106,  318.8306],
         [ 974.0906,  301.0718],
         [ 971.3586,  305.1454],
         [1002.2526,  286.5532],
         [1007.3780,  299.3423],
         [1069.0325,  340.6642],
         [1039.5984,  364.9513],
         [1079.3052,  445.6385],
         [1054.8763,  492.9890],
         [ 988.8803,  500.9942],
         [ 994.7704,  525.5869],
         [1093.5485,  597.9498],
         [1062.3596,  603.2264],
         [1110.8331,  782.7985],
         [1019.2966,  791.3737],
         [1188.2494,  967.1171],
         [1046.5940,  968.1740]],

        [[ 968.9412,  312.6946],
         [ 965.7036,  296.0774],
         [ 961.9008,  297.0003],
         [ 924.7234,  293.1803],
         [ 932.8341,  296.1283],
         [ 889.5348,  365.0839],
         [ 907.4465,  377.6008],
         [ 880.4764,  490.3835],
         [ 923.5833,  511.5803],
         [ 936.0958,  528.8392],
         [ 966.9988,  521.9933],
         [ 890.5332,  607.2466],
         [ 903.7192,  616.1772],
         [ 889.2064,  791.4681],
         [ 904.7345,  806.7505],
         [ 886.5789,  974.6896],
         [ 894.5469,  992.0669]]], device='cuda:0')
video 1/1 (frame 5/66) /home/mcqueen/Documents/YoloV8-LSTM-video-Classification/notebooks/NV_1.mp4: 384x640 2 persons, 8.2ms
tensor([[[ 975.7776,  314.1578],
         [ 977.6042,  296.2968],
         [ 973.6859,  300.5933],
         [1004.1890,  284.8690],
         [1007.2562,  297.7834],
         [1071.7517,  342.7596],
         [1036.7017,  365.5956],
         [1087.9459,  445.5962],
         [1049.7368,  489.5928],
         [ 995.2056,  500.2010],
         [ 994.9973,  526.3871],
         [1093.7257,  598.5464],
         [1059.3975,  603.2368],
         [1111.6243,  784.0508],
         [1018.4863,  791.2169],
         [1189.0311,  967.6884],
         [1046.2875,  968.4915]],

        [[ 965.3363,  310.6646],
         [ 962.5066,  294.2496],
         [ 958.1567,  295.0638],
         [ 922.7838,  293.2385],
         [ 930.7113,  295.9670],
         [ 888.7441,  366.6117],
         [ 907.6262,  378.5789],
         [ 882.0943,  490.4463],
         [ 923.6652,  511.7338],
         [ 937.1790,  529.5645],
         [ 968.3905,  523.6884],
         [ 890.6331,  607.4768],
         [ 904.4545,  616.1299],
         [ 890.2444,  792.2236],
         [ 906.3730,  806.8390],
         [ 888.5015,  974.5197],
         [ 894.6886,  991.0583]]], device='cuda:0')
video 1/1 (frame 6/66) /home/mcqueen/Documents/YoloV8-LSTM-video-Classification/notebooks/NV_1.mp4: 384x640 2 persons, 9.8ms
tensor([[[ 973.4806,  311.8163],
         [ 976.2167,  294.0474],
         [ 971.8352,  297.9147],
         [1005.4594,  283.6428],
         [1007.9021,  295.5307],
         [1073.2244,  345.3561],
         [1037.4337,  365.0264],
         [1088.8914,  453.5383],
         [1050.0720,  491.3022],
         [ 992.9116,  499.7708],
         [ 995.3820,  525.1652],
         [1092.1827,  600.2809],
         [1057.9053,  603.3628],
         [1110.1239,  785.7338],
         [1018.4768,  789.9637],
         [1187.4177,  967.2655],
         [1048.8768,  965.1282]],

        [[ 963.5555,  308.7234],
         [ 961.0750,  292.0326],
         [ 955.4951,  292.9814],
         [ 921.1542,  291.2809],
         [ 925.8338,  294.1683],
         [ 883.9371,  366.7287],
         [ 905.8914,  378.8851],
         [ 876.6974,  491.8547],
         [ 924.4459,  513.2986],
         [ 932.9799,  528.2451],
         [ 970.3574,  522.5386],
         [ 888.0952,  606.7348],
         [ 903.8267,  615.6901],
         [ 890.0768,  791.8573],
         [ 908.7790,  806.4598],
         [ 888.8766,  974.1101],
         [ 894.1256,  990.6959]]], device='cuda:0')
video 1/1 (frame 7/66) /home/mcqueen/Documents/YoloV8-LSTM-video-Classification/notebooks/NV_1.mp4: 384x640 2 persons, 9.4ms
tensor([[[ 972.7921,  303.8852],
         [ 976.8400,  285.6728],
         [ 969.9451,  290.0629],
         [1005.4268,  278.6113],
         [1001.1412,  291.0766],
         [1075.2676,  346.1764],
         [1026.5128,  363.7001],
         [1099.3094,  457.0011],
         [1038.0446,  487.4227],
         [1002.6088,  502.0814],
         [ 996.3741,  523.6800],
         [1091.1089,  600.8616],
         [1048.9185,  603.3599],
         [1110.2522,  785.9991],
         [1013.5511,  788.8777],
         [1186.8335,  966.6464],
         [1045.3247,  965.2767]],

        [[ 965.3372,  304.2933],
         [ 963.5951,  287.8287],
         [ 955.2437,  289.1125],
         [ 926.1544,  288.6577],
         [ 919.2903,  291.2398],
         [ 887.9803,  366.7502],
         [ 900.6698,  376.6840],
         [ 885.7189,  491.2067],
         [ 925.7299,  508.4907],
         [ 937.3870,  528.6497],
         [ 972.3148,  521.4775],
         [ 892.4327,  606.0984],
         [ 902.0495,  614.0504],
         [ 892.9696,  792.8235],
         [ 911.1787,  805.5614],
         [ 891.3055,  975.3737],
         [ 896.5673,  990.6871]]], device='cuda:0')
video 1/1 (frame 8/66) /home/mcqueen/Documents/YoloV8-LSTM-video-Classification/notebooks/NV_1.mp4: 384x640 2 persons, 7.6ms
tensor([[[ 974.4430,  298.6188],
         [ 978.0275,  280.4214],
         [ 972.4429,  284.8489],
         [1004.1636,  275.8851],
         [1004.3656,  288.1509],
         [1075.8733,  346.8510],
         [1027.9349,  362.1609],
         [1106.5896,  461.7687],
         [1043.2903,  487.2022],
         [1004.3561,  501.5688],
         [ 996.4307,  522.5134],
         [1087.4011,  602.2043],
         [1045.5570,  603.2361],
         [1109.1829,  788.3019],
         [1009.9788,  788.8103],
         [1186.6080,  968.4714],
         [1042.2573,  965.0960]],

        [[ 962.3396,  298.2945],
         [ 961.5591,  282.3281],
         [ 950.7726,  284.0447],
         [ 929.0853,  286.7382],
         [ 913.6893,  289.7250],
         [ 898.9268,  367.5275],
         [ 894.5985,  377.0128],
         [ 903.5825,  489.7457],
         [ 923.2717,  506.2556],
         [ 947.3829,  531.9290],
         [ 971.2064,  522.1763],
         [ 900.8770,  605.0378],
         [ 899.6298,  612.3762],
         [ 900.6309,  791.0535],
         [ 912.3745,  803.5012],
         [ 892.5280,  973.8170],
         [ 897.9497,  989.1617]]], device='cuda:0')
video 1/1 (frame 9/66) /home/mcqueen/Documents/YoloV8-LSTM-video-Classification/notebooks/NV_1.mp4: 384x640 2 persons, 9.1ms
tensor([[[ 973.0461,  297.5294],
         [ 977.3304,  279.3951],
         [ 971.2009,  284.1006],
         [1007.0675,  274.9654],
         [1004.8107,  288.0070],
         [1080.7766,  347.1496],
         [1026.8591,  362.8945],
         [1111.5629,  465.3054],
         [1039.1392,  488.6921],
         [1001.6907,  504.2758],
         [ 994.0972,  519.8523],
         [1085.5967,  603.7278],
         [1039.7969,  604.5264],
         [1111.1483,  791.7484],
         [1009.5020,  791.9171],
         [1187.0459,  970.5956],
         [1041.1412,  966.4151]],

        [[ 962.6411,  297.2363],
         [ 961.4810,  281.4116],
         [ 950.4580,  283.2065],
         [ 927.5956,  287.0492],
         [ 910.7206,  290.1349],
         [ 896.4128,  369.9445],
         [ 893.0268,  379.6615],
         [ 905.4331,  493.0526],
         [ 926.2224,  509.7287],
         [ 951.0104,  538.4548],
         [ 974.1513,  527.1087],
         [ 898.8177,  606.0613],
         [ 898.4283,  613.6163],
         [ 901.4834,  791.6224],
         [ 915.5452,  804.2814],
         [ 889.1431,  972.0905],
         [ 896.4994,  987.0665]]], device='cuda:0')
video 1/1 (frame 10/66) /home/mcqueen/Documents/YoloV8-LSTM-video-Classification/notebooks/NV_1.mp4: 384x640 2 persons, 7.1ms
tensor([[[ 974.7623,  298.0795],
         [ 978.9176,  280.0009],
         [ 973.1089,  284.4507],
         [1008.1873,  275.4543],
         [1006.9570,  288.0118],
         [1082.1096,  348.4787],
         [1027.9280,  362.0457],
         [1115.6168,  470.1104],
         [1041.9695,  489.2245],
         [1002.5546,  504.1183],
         [ 996.4181,  519.3018],
         [1083.3723,  604.8564],
         [1037.3672,  604.5829],
         [1110.6604,  794.0300],
         [1008.2305,  792.4257],
         [1190.3645,  971.6266],
         [1043.7292,  966.1935]],

        [[ 955.8914,  299.0988],
         [ 955.3655,  283.7983],
         [ 943.3270,  285.4179],
         [ 925.5215,  291.2163],
         [ 904.4723,  293.3314],
         [ 901.1948,  374.8060],
         [ 886.7028,  383.2992],
         [ 915.8857,  496.1196],
         [ 924.5123,  511.5359],
         [ 957.7180,  539.2480],
         [ 974.5599,  525.9618],
         [ 904.6766,  609.7157],
         [ 897.0864,  616.5586],
         [ 906.0370,  793.6511],
         [ 915.1419,  805.5243],
         [ 889.6299,  972.1844],
         [ 898.1097,  985.5824]]], device='cuda:0')
video 1/1 (frame 11/66) /home/mcqueen/Documents/YoloV8-LSTM-video-Classification/notebooks/NV_1.mp4: 384x640 2 persons, 8.8ms
tensor([[[ 978.6227,  295.7386],
         [ 985.7759,  278.0848],
         [ 975.4224,  282.8842],
         [1022.1926,  273.8875],
         [1004.8606,  287.3854],
         [1094.2791,  347.4239],
         [1019.1549,  362.5244],
         [1126.8115,  462.5524],
         [1018.7301,  479.8911],
         [1011.8776,  496.9727],
         [ 986.2255,  503.7942],
         [1086.1423,  603.4963],
         [1027.6597,  604.1708],
         [1113.6367,  793.0774],
         [1008.8568,  792.4448],
         [1191.4939,  969.5764],
         [1046.8882,  964.2921]],

        [[ 953.1290,  300.7120],
         [ 952.1687,  285.8805],
         [ 940.5704,  287.2737],
         [ 921.0018,  294.0893],
         [ 900.7084,  295.6601],
         [ 894.4427,  376.1887],
         [ 885.5284,  384.6682],
         [ 912.4330,  492.8288],
         [ 926.8341,  508.1779],
         [ 956.6118,  527.5036],
         [ 976.7900,  511.9448],
         [ 901.4897,  609.1280],
         [ 897.5957,  616.1100],
         [ 902.6034,  792.9171],
         [ 916.7928,  804.4612],
         [ 886.5845,  970.8492],
         [ 897.5875,  982.5103]]], device='cuda:0')
video 1/1 (frame 12/66) /home/mcqueen/Documents/YoloV8-LSTM-video-Classification/notebooks/NV_1.mp4: 384x640 2 persons, 10.2ms
tensor([[[ 982.2834,  295.8149],
         [ 990.1854,  278.1328],
         [ 977.9989,  283.0062],
         [1029.6161,  271.4938],
         [1005.2606,  285.7561],
         [1099.2717,  343.9594],
         [1022.3355,  360.8418],
         [1131.9347,  456.2115],
         [1025.1333,  477.9991],
         [1019.6949,  495.8363],
         [ 987.0820,  508.7490],
         [1084.7931,  601.6610],
         [1025.0476,  602.7318],
         [1114.4895,  790.4390],
         [1009.7584,  790.7968],
         [1191.5819,  967.9378],
         [1045.4235,  963.7222]],

        [[ 950.0377,  299.9653],
         [ 949.5489,  284.9337],
         [ 937.2733,  286.4336],
         [ 920.4893,  292.6942],
         [ 897.7496,  294.1693],
         [ 896.0837,  375.0579],
         [ 883.0165,  383.3728],
         [ 915.9895,  489.5335],
         [ 925.0618,  504.8560],
         [ 957.1659,  527.8300],
         [ 972.6614,  512.2548],
         [ 902.7090,  607.8718],
         [ 896.2723,  614.6794],
         [ 904.8372,  790.6287],
         [ 917.7310,  801.9833],
         [ 888.2881,  971.7805],
         [ 900.6083,  982.9872]]], device='cuda:0')
video 1/1 (frame 13/66) /home/mcqueen/Documents/YoloV8-LSTM-video-Classification/notebooks/NV_1.mp4: 384x640 2 persons, 11.3ms
tensor([[[ 985.7294,  294.0744],
         [ 994.2244,  276.8542],
         [ 981.5554,  281.2004],
         [1034.6951,  270.5807],
         [1007.4436,  283.5465],
         [1100.8145,  342.9755],
         [1022.1837,  358.6393],
         [1133.3035,  454.5366],
         [1024.6111,  474.2346],
         [1026.1438,  495.4546],
         [ 988.0587,  505.3225],
         [1084.9904,  601.7012],
         [1024.3308,  602.5059],
         [1115.0027,  790.1342],
         [1010.7183,  789.8168],
         [1191.2034,  968.7451],
         [1046.3883,  962.5697]],

        [[ 946.1534,  300.3029],
         [ 945.0056,  285.4550],
         [ 934.0283,  286.6806],
         [ 913.0253,  293.0711],
         [ 895.1758,  294.0367],
         [ 886.0842,  374.3622],
         [ 883.3931,  381.8893],
         [ 905.1084,  484.5802],
         [ 926.5809,  498.1533],
         [ 952.0922,  525.4357],
         [ 972.1496,  510.0598],
         [ 897.7830,  606.0898],
         [ 898.0527,  613.0139],
         [ 903.0762,  788.2869],
         [ 920.6393,  799.3737],
         [ 889.7019,  971.3586],
         [ 903.1989,  982.5170]]], device='cuda:0')
video 1/1 (frame 14/66) /home/mcqueen/Documents/YoloV8-LSTM-video-Classification/notebooks/NV_1.mp4: 384x640 2 persons, 9.7ms
tensor([[[ 981.5254,  284.7948],
         [ 991.2615,  267.4423],
         [ 977.7647,  272.2058],
         [1034.9067,  263.7384],
         [1005.4982,  277.3231],
         [1103.3207,  340.2989],
         [1018.2688,  356.9166],
         [1137.9082,  453.5746],
         [1018.5995,  475.0258],
         [1029.1044,  489.1808],
         [ 987.7662,  501.8383],
         [1084.1699,  601.8048],
         [1019.6439,  602.7853],
         [1115.7251,  789.1544],
         [1009.2014,  788.8855],
         [1191.5122,  967.9102],
         [1046.9197,  961.5510]],

        [[ 948.8169,  300.4296],
         [ 943.3837,  286.6037],
         [ 937.0168,  286.7610],
         [ 900.8877,  293.6169],
         [ 895.7279,  294.1448],
         [ 874.5972,  368.8419],
         [ 885.9108,  379.2852],
         [ 905.9850,  472.1040],
         [ 931.0296,  500.3948],
         [ 963.6616,  499.3626],
         [ 978.4443,  502.9633],
         [ 886.5552,  603.0615],
         [ 896.0403,  610.7178],
         [ 896.9537,  791.3698],
         [ 923.0352,  803.2186],
         [ 881.0221,  975.2866],
         [ 891.8104,  986.5634]]], device='cuda:0')
video 1/1 (frame 15/66) /home/mcqueen/Documents/YoloV8-LSTM-video-Classification/notebooks/NV_1.mp4: 384x640 2 persons, 8.4ms
tensor([[[ 981.2053,  282.6104],
         [ 991.7362,  265.9716],
         [ 977.1940,  269.8571],
         [1032.5989,  266.5461],
         [1003.1019,  277.3300],
         [1090.2285,  349.6382],
         [1021.9455,  360.8148],
         [1124.0265,  469.0780],
         [1024.1908,  479.5507],
         [1029.0007,  490.2725],
         [ 998.6010,  499.8855],
         [1082.8079,  604.6799],
         [1032.1094,  603.4364],
         [1098.6377,  797.2121],
         [1009.2621,  792.1247],
         [1174.3008,  981.5187],
         [1042.2863,  970.8192]],

        [[ 945.4160,  305.0916],
         [ 938.7944,  291.1305],
         [ 934.5097,  291.2415],
         [ 891.3727,  298.0079],
         [ 895.8429,  298.9920],
         [ 864.1827,  371.9244],
         [ 889.2955,  381.8690],
         [ 896.1265,  471.5858],
         [ 933.0549,  497.3871],
         [ 959.0729,  495.5939],
         [ 979.3961,  499.0704],
         [ 878.5172,  604.1511],
         [ 897.1023,  611.7960],
         [ 892.1332,  791.7816],
         [ 924.2955,  803.5066],
         [ 879.1560,  972.0769],
         [ 890.7471,  985.0032]]], device='cuda:0')
video 1/1 (frame 16/66) /home/mcqueen/Documents/YoloV8-LSTM-video-Classification/notebooks/NV_1.mp4: 384x640 2 persons, 8.3ms
tensor([[[ 980.1363,  280.1746],
         [ 991.0767,  263.6544],
         [ 975.9441,  267.6406],
         [1032.6012,  265.1608],
         [1000.9855,  276.1270],
         [1092.7708,  348.8462],
         [1017.0547,  358.9889],
         [1127.1954,  468.7817],
         [1015.4097,  476.2432],
         [1030.4225,  491.8883],
         [ 998.8666,  501.5626],
         [1084.3535,  603.2584],
         [1028.6897,  601.8609],
         [1102.6499,  795.8488],
         [1008.9729,  790.2887],
         [1176.8284,  980.4353],
         [1040.7518,  970.4341]],

        [[ 943.7646,  305.4616],
         [ 937.5544,  291.5659],
         [ 932.8516,  291.4093],
         [ 890.7275,  299.5843],
         [ 897.4327,  300.5640],
         [ 865.1892,  373.4044],
         [ 892.2306,  382.5777],
         [ 893.8418,  471.1011],